all:
	gcc -lpthread memleak.c -omemleak
	gcc -lpthread memleakfix1.c -omemleakfixed1
	gcc -lpthread memleakfix2.c -omemleakfixed2
	gcc -lpthread memleakfix3.c -omemleakfixed3
clean:
	rm memleak memleakfixed
